const ActionTypes = {
  FORM_SUBMIT: 'FORM_SUBMIT',
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_USER_IMAGE: 'UPDATE_USER_IMAGE'
};

export { ActionTypes };
