const ActionTypes = {
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  GET_USER_PROFILE_SIDEBAR: 'GET_USER_PROFILE_SIDEBAR',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_USER_IMAGE: 'UPDATE_USER_IMAGE'
};

export { ActionTypes };
